name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  action-environment-debug:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
    # - uses: actions/setup-node@v4
      #   with:
      #     node-version: '20'

      - name: Test run
        run: | 
          date
          ls -la
          pwd 
          echo "TEST---------------------------------"
          env
      - run: npm install --global surge
      - run: surge --version
      - run: date >> README.md
      - run: npm install
        working-directory: ./web-frontend/
      - run: npm run build
        working-directory: ./web-frontend/
      - name: Surge deploy
        working-directory: ./web-frontend/
        run: | 
          date
          ls -la
          pwd 
          echo "CIAO---------------------------------"
          env
      - run: echo "Fineeeeeeeeeeeeeeeeeeeeeeeeeeee"